project_name: draupnir
release:
  github:
    owner: gocardless
    name: draupnir
  name_template: '{{.Tag}}'
brew:
  github:
    owner: gocardless
    name: homebrew-taps
  commit_author:
    name: Harry Maclean
    email: harrymaclean@gocardless.com
  install: bin.install "draupnir-client"
  description: Client for the draupnir database service
  folder: Formula
  test: system "draupnir-client help"
builds:
- 
  main: ./main.go
  binary: draupnir
  goos:
  - linux
  - darwin
  main: .
  ldflags: -s -w -X github.com/gocardless/draupnir/version.Version={{.Version}} -X main.commit={{.Commit}}
-
  binary: draupnir-client
  main: ./cli/main.go
  ldflags: -s -w -X github.com/gocardless/draupnir/version.Version={{.Version}} -X main.commit={{.Commit}}
  goos:
  - linux
  - darwin
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
  - README*
  - CHANGELOG*
fpm:
  maintainer: GoCardless Engineering <engineering@gocardless.com>
  description: Databases on demand
  formats: [deb]
  bindir: /usr/local/bin
  files:
    "cmd/draupnir-create-instance": "/usr/local/bin/draupnir-create-instance"
    "cmd/draupnir-destroy-instance": "/usr/local/bin/draupnir-destroy-instance"
    "cmd/draupnir-finalise-image": "/usr/local/bin/draupnir-finalise-image"
    "cmd/draupnir-destroy-image": "/usr/local/bin/draupnir-destroy-image"
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
