[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/google/jsonapi"
  revision = "925ebf2136461bb9d121340ec95a719bf9073d1c"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/burntsushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
