database_url = "host=/run/postgresql user=draupnir dbname=draupnir"
data_path = "/data"
environment = "development"
shared_secret = "the_shared_secret"
trusted_user_email_domain = "@gocardless.com"
public_hostname = "localhost"
clean_interval = "30m"
enable_ip_whitelisting = true
whitelist_reconcile_interval = "20m"
min_instance_port = 7432
max_instance_port = 8432
use_x_forwarded_for = true
trusted_proxy_cidrs = ["10.164.0.0/16"]

[http]
listen_address = "0.0.0.0:8443"
insecure_listen_address = "127.0.0.1:8080"
tls_certificate = "/etc/ssl/certs/ssl-cert-snakeoil.pem"
tls_private_key = "/etc/ssl/private/ssl-cert-snakeoil.key"

[oauth]
redirect_url = "https://example.com/oauth_callback"
client_id = "client_id"
client_secret = "client_secret"
