---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/gocardless/draupnir
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure -v && dep prune && test -z "$(git status --porcelain -- Gopkg.toml Gopkg.lock vendor)"
      - run: mkdir -p $TEST_RESULTS
      - run: make test
      - run: make build-production
      - run: make client
  rubocop:
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/draupnir
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
workflows:
  version: 2
  tests:
    jobs:
      - build
      - rubocop
