version: 2
jobs:
  build:
    machine: true
    environment:
      KNIFE_ENV: test
    working_directory: /go/src/github.com/gocardless/draupnir
    steps:
      - checkout
      - run:
          name: Install Gom
          command: go get github.com/mattn/gom
      - run:
          command: gom install
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby bundle
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          paths:
            - vendor/bundle
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Setup cookbook
          command: make setup-cookbook
      - run:
          name: Unit Tests
          command: make test
      - run:
          name: Integration Tests
          command: make test-integration
